console.log('test')

//setting constants for accessing elements w/ DOM
const mainContent = document.querySelector('#main-content')
const projectsContent = document.querySelector('#projects-content')
const bioContent = document.querySelector('#projects-content')
const resumeContent = document.querySelector('#resume-content')
const contactMeContent = document.querySelector('contact-me-content')
const homeHead = document.querySelector('#home-head')
const bioHead = document.querySelector('#bio-head')
const resumeHead = document.querySelector('#resume-head')
const projectsHead = document.querySelector('#projects-head')
const contactMeHead = document.querySelector('#contact-me-head')
const brandStatement = document.querySelector('#brand-statement')
const bioButtons = document.querySelector('#bio-buttons')
const sportsButton = document.querySelector('#sports-button')
const GamingButton = document.querySelector('#gaming-button')
const foodButton = document.querySelector('#food-button')
const musicButton = document.querySelector('#music-button')
const selfie = document.querySelector('#selfie')
const navLinks = document.querySelector('#nav-links')
const navButtons = document.querySelector('#nav-buttons')